# Generated by Django 5.1.6 on 2025-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default='products/default_products.jpeg', upload_to='products/products_image/'),
        ),
    ]
