# Generated by Django 5.1.6 on 2025-02-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
